# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "sd_mod" "xhci_hcd" "xhci_pci" "usb_storage" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "kvm-intel" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "snd_hda_intel" "snd_soc_skl" "vulkan_intel" ];
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b85606ed-9c49-49e8-84b3-748e0f81388b";
      fsType = "ext4";
    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/96ceed18-99c6-443c-86ad-6979a4aa4a51";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/05B4-0F0C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/234ab296-8487-4a92-9e11-05cc0f098ab0"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
